### ISSUE TITLE
Should skip rendering custom components inside code block

### ISSUE THREAD

**Issue by pierrecholhot** [storybooks/marksy#26]
First of all, Kudos for this great project ! 👍 

----

I created a custom component `<Image source="" legend="" />` that works as intended.

The issue occurs when I'm trying to show this source code above the image. I'm using GFM Code blocks (and have GFM enabled in marked):

```
    ```
    <Image source="" legend="" />
    ```
```

**It is impossible to see the "code".** It gets rendered and replaced by a chunk of the actual HTML (Inspecting the output, I have `<img source="" legend="" />`).

**One workaround I found is:**

```
    ```
    &lt;Image source="" legend="" />
    ```
```

I don't know if this is intended or a bug?

**Update:**
Inline code blocks do not have this issue..

**Comment by marbemac** [comment]
I believe this is intended, see https://github.com/cerebral/marksy#custom-components - specifically the example of this in the code sample.

This is so that the markdown is considered valid when rendered by other parsers (such as embedding in a github readme). Github will render it as a normal code block, without evaluation of the custom component.

**Comment by Hypnosphi** [comment]
The issue (and a potential XSS vulnerability) is that `dangerouslySetInnerHTML` is used instead of `children`: https://github.com/cerebral/marksy/blob/master/src/createRenderer.js#L58

This wouldn't be such a big problem if you were able to pass your own component as `CodeComponent`, but unfortunately you can't: https://github.com/cerebral/marksy/issues/38

You can pass `highlight` option and do some escaping there though:
```
import marksy from 'marksy'
import hljs from 'highlight.js'
import escapeHtml from 'escape-html'

const compile = marksy({
  createElement: React.createElement,
  highlight(language, code) {
    const escapedCode = escapeHtml(code)
    return hljs.highlight(language, escapedCode).value
  },
})
```

**Comment by christianalfoni** [comment]
@Hypnosphi That would be great! Interested in helping out with it? I am in serious lack of time, but using this project for multiple of my own/work projects... so want to keep it running :)

**Comment by Hypnosphi** [comment]
We have published our fork with the fix from #46: https://www.npmjs.com/package/@storybook/marksy

**Comment by christianalfoni** [comment]
@Hypnosphi If you want I can give you access to this repo... if you want to merge efforts. Or I would be happy to point users to `@storybook/marksy` instead... I just want the project to get some love, which I am in lack of these days :)

**Comment by Hypnosphi** [comment]
I'm OK with both. The former makes more sense to me though

**Comment by Hypnosphi** [comment]
@christianalfoni Thanks. I'd like to setup some CI integration, but looks like I don't have enough rights =(

Sou maybe it would be more convenient if this repo would be owned by `storybooks` organisation. I hope you don't mind if we transfer the ownership

**Comment by Hypnosphi** [comment]
@christianalfoni can you please give me access to publishing npm package as well?
https://www.npmjs.com/package/marksy/access
https://www.npmjs.com/~hypnosphi

**Comment by christianalfoni** [comment]
Done :)
